# Generated by Django 3.1.4 on 2021-01-23 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifytoken',
            name='access_token',
            field=models.CharField(default='null', max_length=150),
            preserve_default=False,
        ),
    ]
